language: python
python:
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install: "pip install --process-dependency-links git+https://github.com/pymc-devs/pymc3"
# command to run tests
script: "tests/linear_regression_tests"
